# Generated by Django 5.2.10 on 2026-01-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrainingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="pending", max_length=50)),
                ("config", models.JSONField(default=dict)),
                ("metrics", models.JSONField(blank=True, default=dict, null=True)),
                ("log", models.TextField(blank=True)),
                ("checkpoint_path", models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
